version: '3'

services:
  app:
    build: .
    entrypoint: go run cmd/main.go
    volumes:
      - .:/go/src
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    environment:
      - BOOTSTRAP_SERVERS=host.docker.internal:9094